config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :publics, controllers: {
  sessions:      'publics/sessions',
  passwords:     'publics/passwords',
  registrations: 'publics/registrations'
}
  root 'public/homes#top'

  scope module: :public do
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :cart_items, only: [:index, :update, :destroy,:create]
  delete 'cart_items' => 'cart_items#destroy_all'
  resources :end_users, only: [:show, :edit, :update]
  get 'end_users' => 'end_users#unsubscribe'
  patch 'end_users' => 'end_users#withdraw'
  resources :items, only: [:index, :show]
  resources :orders, only: [:new, :create, :index, :show]
  post 'orders' => 'orders#confirm'
  get 'orders' => 'orders#complete'
  get 'top' => 'homes/#top'
  get 'about' => 'homes/#about'
  end
  namespace :admin do
  resources :end_users, only:[:index, :show, :edit, :update]
  resources :genres, only:[:index, :create, :edit, :update]
  resources :items, only:[:index, :new, :create, :show, :edit, :update]
  resources :order_details, only:[:update]
  resources :orders, only:[:index, :show, :update]
  get 'top' => 'homes/#top'
  end
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :item
	belongs_to :public
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, dependent: :destroy
    enum is_active: {有効: true, 無効: false}
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre
	has_many :cart_item
	has_many :order_detail
	attachment :image
	enum is_active: {販売中: true, 売切れ: false}
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	has_many :order_detail
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :item
end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # enum is_deleted: {Invalid: true, Available: false}

  def active_for_authentication?
  	super && !self.is_deleted # 有効: TRUE, 無効: FALSE
  end
end


# TRUE AND(&&) TRUE => TRUE
# TRUE AND FALSE => FALSE
# FALSE AND FALSE => FALSE

# TRUE OR(||) TRUE => TRUE
# TRUE OR FALSE => TRUE
# FALSE OR FALSE => FALSE

# NOT(!)

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
	def index
		@genres = Genre.all
		@genre = Genre.new
	end
	def create
		@genre = Genre.new(genre_params)
		@genre.save
		redirect_to admin_genres_path
	end
	def edit
		@genre = Genre.find(params[:id])
	end
	def update
        genre = Genre.find(params[:id])
		genre.update(genre_params)
		redirect_to admin_genres_path
	end
	private
    def genre_params
    	params.require(:genre).permit(:name, :is_active)
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	def index
		@items = Item.all
	end
	def new
		@item = Item.new
	end
	def create
		@item = Item.new(item_params)
		@item.save
		redirect_to admin_item_path(@item)
	end
	def show
		@item = Item.find(params[:id])
	end
	def edit
		@item = Item.find(params[:id])
	end
	def update
		@item = Item.find(params[:id])
		@item.update(item_params)
		redirect_to admin_item_path(@item.id)
	end
	private
    def item_params
    	params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
      items_path
  end
  def after_sign_out_path_for(resource)
      new_public_session_path
  end
 
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted])
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<%= form_for(@genre, url: admin_genre_path(@genre),method: :patch) do |f| %>
<h2>ジャンル編集</h2>
	<b>ジャンル</b>
			    <%= f.text_field :name, id:"inputtext" %>
			    <%= f.select :is_active, Genre.is_actives.keys, class:"form-control" %>
			    <%= f.submit "変更を保存する" %>

<% end %>

app/views/admin/genres/index.html.erb
<div class="row">
  <%= form_for(@genre, url: admin_genres_path) do |f| %>
        <%= f.label :name, 'ジャンル' %>
        <%= f.text_field :name, class:'form-control' %>
        <%= f.select :is_active, Genre.is_actives.keys, class:"form-control" %>
        <%= f.submit '追加', class: 'btn btn-primary btn-block' %>
  <% end %>
<br>
  <div class="col-xs-9">
      <div class="block-title">
              <table class="table">
                <thead>
                  <tr>
                    <th>ジャンル</th>
                    <th>状態</th>
                    <th></th>
                  </tr>
                </thead>

                <tbody>
                  <% @genres.each do |genre| %>
                    <tr>
                      <td>
                        <%= genre.name %>
                     </td>
                      <td>
                        <%= genre.is_active %>
                      </td>
                      <td>
                        <%= link_to "編集", edit_admin_genre_path(g.id), class: "btn btn-success btn-sm" %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
               </table>
            </div>
      </div>
</div>

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>
<%= form_for(@item, url: admin_item_path(@item)) do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.attachment_field :image %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group has-icon">
        <label class="control-label sr-only">商品名　</label>
        <%= f.text_field :name, class:"form-control" %>
        <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <label class="control-label sr-only">商品説明</label>
      <%= f.text_area :introduction, class:"form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <%= f.label :genre, 'ジャンル' %>
      <%= f.select :genre_id, Genre.all.map{|o| [o.name, o.id]} %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <label class="control-label sr-only">税抜価格</label>
      <%= f.text_field :price, class:"form-control" %>円
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <%= f.label :is_active, '販売ステータス' %>
      <%= f.select :is_active, Item.is_actives.keys, { class: 'form-control' , required: true } %>
    </div>
  </div>
  <hr>
    <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>

app/views/admin/items/index.html.erb
<h2>商品一覧</h2>
<div class="row">
	<div class="col-xs-9">
		<table class="table">
			<thead>
				<tr>
					<th scope="col">商品ID</th>
					<th scope="col">商品名</th>
					<th scope="col">税抜価格</th>
					<th scope="col">ジャンル</th>
					<th scope="col">ステータス</th>
				</tr>
			</thead>
			<tbody>
				<% @items.each do |item| %>
				<tr>
					<td><%= item.id %></td>
					<td>
						<%= link_to admin_item_path(item.id) do %>
						<%= item.name %>
						<% end %>
						</td>
					<td><%= item.price %></td>
					<td><%= item.genre.name %></td>
					<td><%= item.is_active %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/items/new.html.erb
<%= form_for(@item, url: admin_items_path) do |f| %>
  <div class="container">
    <div class="row">
      <h2>商品新規登録</h2>
          <div class="col-md-3 col-sm-3 col-xs-12">
            <%= f.attachment_field :image %>
          </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
                <label>商品名</label>
                <%= f.text_field :name, class:"form-control" %>
                <label>商品説明</label>
                <%= f.text_area :introduction, class:"form-control" %>
                <%= f.label :genre, 'ジャンル' %>
                <%= f.select :genre_id, Genre.all.map{|o| [o.name, o.id]} %>
                <label>税抜価格</label>
                <%= f.text_field :price, class:"form-control" %>円<br>
                <%= f.label :is_active, '販売ステータス' %>
                <%= f.select :is_active, Item.is_actives.keys, { class: 'form-control' , required: true } %>
            </div>
              <div class="col-md-3 col-sm-3 col-xs-12">
                <%= f.submit "新規登録"%>
              </div>
      </div>
    </div>
  <% end %>

app/views/admin/items/show.html.erb
<div class="container">
	<h2>商品詳細</h2>
		<div class="row">
			<div class="col-md-3 col-sm-3 col-xs-12">
					<%= attachment_image_tag @item, :image , :fill,200 ,200  %>
		    </div>
		    	<div class="col-md-6 col-sm-6 col-xs-12">
						<table class="table">
								<tr>
									<td>商品名</td><td><%= @item.name %></td>
								</tr>
								<tr>
									<td>商品説明</td><td><%= @item.introduction %></td>
								</tr>
								<tr>
									<td>ジャンル</td><td><%= @item.genre_id %></td>
								</tr>
								<tr>
									<td>税込価格（税抜価格）</td><td>（<%= @item.price %>）円</td>
								</tr>
								<tr>
									<td>販売ステータス</td><td><%= @item.is_active %></td>
								</tr>
						</table>
				</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<%= link_to "編集", edit_admin_item_path(@item) %>
					</div>
		</div>
</div>