config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :publics, controllers: {
  sessions:      'publics/sessions',
  passwords:     'publics/passwords',
  registrations: 'publics/registrations'
}
  root 'public/homes#top'

  scope module: :public do
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :cart_items, only: [:index, :update, :destroy,:create]
  delete 'cart_items' => 'cart_items#destroy_all'
  resources :end_users, only: [:show, :edit, :update]
  get 'end_users' => 'end_users#unsubscribe'
  patch 'end_users' => 'end_users#withdraw'
  resources :items, only: [:index, :show]
  resources :orders, only: [:new, :create, :index, :show]
  post 'orders' => 'orders#confirm'
  get 'orders' => 'orders#complete'
  get 'top' => 'homes/#top'
  get 'about' => 'homes/#about'
  end
  namespace :admin do
  resources :end_users, only:[:index, :show, :edit, :update]
  resources :genres, only:[:index, :create, :edit, :update]
  resources :items, only:[:index, :new, :create, :show, :edit, :update]
  resources :order_details, only:[:update]
  resources :orders, only:[:index, :show, :update]
  get 'top' => 'homes/#top'
  end
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :item
	belongs_to :public
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, dependent: :destroy
    enum is_active: {有効: true, 無効: false}
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre
	has_many :cart_item
	has_many :order_detail
	attachment :image
	enum is_active: {販売中: true, 売切れ: false}
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	has_many :order_detail
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :order
	belongs_to :item
end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # enum is_deleted: {Invalid: true, Available: false}

  def active_for_authentication?
  	super && !self.is_deleted # 有効: TRUE, 無効: FALSE
  end
end


# TRUE AND(&&) TRUE => TRUE
# TRUE AND FALSE => FALSE
# FALSE AND FALSE => FALSE

# TRUE OR(||) TRUE => TRUE
# TRUE OR FALSE => TRUE
# FALSE OR FALSE => FALSE

# NOT(!)

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
	def index
		@genres = Genre.all
		@genre = Genre.new
	end
	def create
		@genre = Genre.new(genre_params)
		@genre.save
		redirect_to admin_genres_path
	end
	def edit
		@genre = Genre.find(params[:id])
	end
	def update
        genre = Genre.find(params[:id])
		genre.update(genre_params)
		redirect_to admin_genres_path
	end
	private
    def genre_params
    	params.require(:genre).permit(:name, :is_active)
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	def index
		@items = Item.all
	end
	def new
		@item = Item.new
	end
	def create
		@item = Item.new(item_params)
		@item.save
		redirect_to admin_item_path(@item)
	end
	def show
		@item = Item.find(params[:id])
	end
	def edit
		@item = Item.find(params[:id])
	end
	def update
		@item = Item.find(params[:id])
		@item.update(item_params)
		redirect_to admin_item_path(@item.id)
	end
	private
    def item_params
    	params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
      items_path
  end
  def after_sign_out_path_for(resource)
      new_public_session_path
  end
 
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_deleted])
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="row">
      <div class="navbar-header">
        <span class="title">Bookers</span>
      </div>
        <% if public_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-list">
              <%= link_to 'マイページ', end_user_path(current_public), class:"glyphicon glyphicon-user" %>
            </li>
           <li class="nav-list">
              <%= link_to '商品一覧', items_path, class:"glyphicon glyphicon-book" %>
            </li>
            <li class="nav-list">
              <%= link_to "logout", destroy_public_session_path, method: :delete , class:"glyphicon glyphicon-log-out"%>
            </li>
          </ul>
         <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-list">
              <%#= link_to 'About', home_about_path, class:"glyphicon glyphicon-link" %>
            </li>
            <li class="nav-list">
              <%= link_to '商品一覧', items_path, class:"glyphicon glyphicon-book" %>
            </li>
            <li class="nav-list">
              <%= link_to "新規登録",new_public_registration_path, class:"glyphicon glyphicon-edit" %>
            </li>
            <li class="nav-list">
              <%= link_to "ログイン",new_public_session_path, class:"glyphicon glyphicon-log-in" %>
            </li>
          </ul>
          <% end %>
      </div>
    </div>
</header>



<div class="container">
  <br>
  <br>
  <br>

  <%= yield %>
</div>
</body>
</html>